### ISSUE TITLE
aaa cert File not found

### ISSUE THREAD

**Issue by iwalz** [nabeken/aaa#10]
Hey,

I'm currently trying to integrate aaa into my environment - but I couldn't make it so far ...
I followed the documentation and reg and authz were working perfectly - but once I schedule the cert command, I got the following error:

```
2016/07/30 22:38:01 INFO: now issuing certificate...
2016/07/30 22:38:01 INFO: loading existing private key...
2016/07/30 22:38:01 ERROR: aaa: file not found
```

Here are the commands I use:

```
golang/bin/aaa reg --email foo@bar.com --s3-bucket foo --s3-kms-key xx-xx-xx-xx-xxxxxx --agree https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf
```

```
golang/bin/aaa authz --email foo@bar.com --s3-bucket foo --s3-kms-key xx-xx-xx-xx-xxxxxx --domain aws.example.com --challenge dns-01
```

```
golang/bin/aaa cert --email foo@bar.com --s3-bucket foo --s3-kms-key xx-xx-xx-xx-xxxxxx --cn aws.example.com
```

ls also gives a similar error:

```
golang/bin/aaa ls --s3-bucket foo --s3-kms-key  xx-xx-xx-xx-xxxxxx
2016/07/30 22:43:11 failed to load certificate for aws.example.com: aaa: file not found (or new-cert is ongoing or this domain is in SAN in other certificates). skipping...
[]
```

The behaviour is the same for staging and production of letsencrypt.

It would be great if you can point me somehow to the right direction, I like the ideas behind this tool and would like to use it vs building kind of the same thing :-)

**Comment by nabeken** [comment]
@iwalz Thanks for trying `aaa` 😄  I found that README was not updated and I've just fixed some inconsistency in the command-line flag.

Could you update `aaa` command with `go get -u` and try the below?

``` sh
# adding --create-key will work for you
golang/bin/aaa cert --email foo@bar.com --s3-bucket foo --s3-kms-key xx-xx-xx-xx-xxxxxx --cn aws.example.com --create-key
```

**Comment by nabeken** [comment]
Finally, `aaa` now creates a key pair automatically if it does not exit on S3.
